name: "Help improve documentation"
description: Report issues in our documentation.
title: "Documentation: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: textarea
    attributes:
      label: Provide a description of requested docs changes
      placeholder: Briefly describe which document needs to be corrected and why.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's [Code of Conduct](https://github.com/RyanLua/Shime?tab=coc-ov-file)
          required: true
