name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:

  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: ok-nick/setup-aftman@v0.3.0
        name: Install aftman
        with: 
          token: ${{ SECRETS.GITHUB_TOKEN }} 

      - name: Run selene
        run: |
          selene ./src

   style:
     name: Run styler
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3
       - name: Run stylua
         uses: JohnnyMorganz/stylua-action@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           version: latest
           args: --check ./src